# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'
# source 'git@github.com:CocoaPods/Specs.git'

platform:ios,'13.0'
inhibit_all_warnings!

target 'CYLTabBarController-Swift' do
  use_frameworks!
 pod 'CYLTabBarController', :path => '../'
end
 
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "13.0"
    end
  end
end
