# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CYLTabBarController-Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
#  pod 'CYLTabBarController', '1.99.4'
#  pod 'CYLTabBarContr oller', :path => '../'
  pod 'CYLTabBarController/Lottie', :path => '../'

  # Pods for CYLTabBarController-Swift

end
