# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#source 'https://github.com/CocoaPods/Specs.git'

target 'HealthyHome' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HealthyHome

#  pod 'CYLTabBarController'
  pod 'CYLTabBarController', :path => '../'





  target 'HealthyHomeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HealthyHomeUITests' do
    # Pods for testing
  end

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "13.0"
    end
  end
end
