/*
 //  CYLFlatDesignTabBarController
 //  CYLFlatDesignTabBarController
 //
 //  Created by 微博@iOS程序犭袁 ( http://weibo.com/luohanchenyilong/ ) on 03/06/19.
 //  Copyright © 2026 https://github.com/ChenYilong . All rights reserved.
 */

import UIKit

/// CYLFlatDesignTabBarItem inherits from UITabBarItem, the purpose is to provide UITabBarItem property settings for CYLFlatDesignTabBarItemContentView.
/// Support most commonly used attributes, such as image, selectedImage, title, tag etc.
///
/// Unsupport properties:
/// MARK: UIBarItem properties
///     1. var landscapeImagePhone: UIImage?
///     2. var imageInsets: UIEdgeInsets
///     3. var landscapeImagePhoneInsets: UIEdgeInsets
///     4. func setTitleTextAttributes(_ attributes: [String : Any]?, for state: UIControlState)
///     5. func titleTextAttributes(for state: UIControlState) -> [String : Any]?
/// MARK: UITabBarItem properties
///     1. func setBadgeTextAttributes(_ textAttributes: [String : Any]?, for state: UIControlState)
///     2. func badgeTextAttributes(for state: UIControlState) -> [String : Any]?
///
@available(iOS 8.0, *)
open class CYLFlatDesignTabBarItem: UITabBarItem {
    
    // MARK: UIView properties
    
    /// The receiver’s tag, an application-supplied integer that you can use to identify bar item objects in your application. default is `0`
    open override var tag: Int
    {
        didSet { self.contentView.tag = tag }
    }
    
    // MARK: UIBarItem properties
    
    /// A Boolean value indicating whether the item is enabled, default is `YES`.
    open override var isEnabled: Bool
    {
        didSet { self.contentView.enabled = isEnabled }
    }
    
    /// The title displayed on the item, default is `nil`
    open override var title: String?
    {
        didSet { self.contentView.title = title }
    }
    
    /// The image used to represent the item, default is `nil`
    open override var image: UIImage?
    {
        didSet { self.contentView.image = image }
    }
    
    // MARK: UITabBarItem properties
    
    /// The image displayed when the tab bar item is selected, default is `nil`.
    open override var selectedImage: UIImage?
    {
        get { return contentView.selectedImage }
        set(newValue) { contentView.selectedImage = newValue }
    }
    
    /// Text that is displayed in the upper-right corner of the item with a surrounding red oval, default is `nil`.
    open override var badgeValue: String?
    {
        get { return contentView.badgeValue }
        set(newValue) { contentView.badgeValue = newValue }
    }
    
    /// The offset to use to adjust the title position, default is `UIOffset.zero`.
    open override var titlePositionAdjustment: UIOffset
    {
        get { return contentView.titlePositionAdjustment }
        set(newValue) { contentView.titlePositionAdjustment = newValue }
    }
    
    /// The background color to apply to the badge, make it available for iOS8.0 and later. If this item displays a badge, this color will be used for the badge's background. If set to nil, the default background color will be used instead.
    @available(iOS 8.0, *)
    open override var badgeColor: UIColor? {
        get { return contentView.badgeColor }
        set(newValue) { contentView.badgeColor = newValue }
    }
    
    // MARK: CYLFlatDesignTabBarItem properties
    
    /// Customize content view, default is `CYLFlatDesignTabBarItemContentView`
    open var contentView: CYLFlatDesignTabBarItemContentView = CYLFlatDesignTabBarItemContentView()
    {
        didSet {
            self.contentView.updateLayout()
            self.contentView.updateDisplay()
        }
    }
    
    /*!
     setting the contentView properties as a result of calling the setters on ESTabBarItem.

     * let item = ESTabBarItem(
                BounceTabBarItem(),
                title: "My Tab",
                image: .imageAsset,
                selectedImage: .activeImageAsset,
                tag: 7
            )
     print(item.tag) //prints 0. 7 is expected
     print(item.contentView.tag) // prints 7
     */
    /// The unselected image is autogenerated from the image argument. The selected image is autogenerated from the selectedImage if provided and the image argument otherwise. To prevent system coloring, provide images with UIImageRenderingModeAlwaysOriginal (see UIImage.h)
    public init(_ contentView: CYLFlatDesignTabBarItemContentView = CYLFlatDesignTabBarItemContentView(), title: String? = nil, image: UIImage? = nil, selectedImage: UIImage? = nil, tag: Int = 0) {
        super.init()
        self.contentView = contentView
//        self.contentView.title = title
//        self.contentView.image = image
//        self.contentView.selectedImage = selectedImage
//        self.contentView.tag = tag
        self.setTitle(title, image: image, selectedImage: selectedImage, tag: tag)
    }
    
    /*!
     * If the calls are made to set the title, image, selectedImage and tag on self they are propagated to the contentView in didSet.
     */
    open func setTitle(_ title: String? = nil, image: UIImage? = nil, selectedImage: UIImage? = nil, tag: Int = 0) {

            self.title = title
            self.image = image
            self.selectedImage = selectedImage
            self.tag = tag
        }
    
    public required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
}
